version: '3'

services:
  traefik:
    image: traefik:v2.7
    command:
      - '--api.insecure=true'
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:8081'
      - '--entrypoints.websecure.address=:8443'
    ports:
      - '8081:8081' # Traefik 대시보드 포트
      - '8443:8443' # HTTPS 포트
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
